name: Deploy Shiny app

on:
  push:
    branches:
      [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies (App Only)
        run: |
           Rscript -e "install.packages('pak', repos = 'https://cloud.r-project.org')"
           Rscript -e "pak::pkg_install(c('shiny', 'data.table', 'dplyr', 'ggplot2', 'readr', 'here', 'DT'))"
      
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        run: |
          Rscript -e "library(rsconnect); rsconnect::setAccountInfo(name='${SHINYAPPS_ACCOUNT}', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"
          Rscript -e "rsconnect::deployApp('.', appName='Damage', account='${SHINYAPPS_ACCOUNT}')"
