name: Update data

on:
  schedule:
    - cron: "0 5 * * *"  # every day at 12:00 UTC
  workflow_dispatch:      # allows manual runs too

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev


      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::remotes
            any::data.table
            any::here
            tidyverse
            httr
            jsonlite
            shiny
            rsconnect

      - name: Install CatBoost manually
        run: |
          Rscript -e 'remotes::install_github("catboost/catboost", subdir = "catboost/R-package")'

      - name: Run Grand Poobah Script
        run: Rscript "Grand Poobah Script.R"

      - name: Commit and push updated data
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/
          git commit -m "Auto-update data [skip ci]" || echo "No changes to commit"
          git push
