name: Update data

on:
  schedule:
    - cron: "0 5 * * *"  # every day at 12:00 UTC
  workflow_dispatch:      # allows manual runs too

jobs:
  update-data:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Grand Poobah Script
        run: Rscript "Grand Poobah Script.R"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}

      - name: Commit and push updated data
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/
          git commit -m "Auto-update data [skip ci]" || echo "No changes to commit"
          git push
